[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = [
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
    "-C", "no-redzone",
    "-C", "panic=abort",
    "-C", "target-feature=-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-avx,-avx2",
    "-C", "target-feature=+soft-float",
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=0x1000"
]
