[package]
name = "chrono-kernel-core"
version = "0.1.0"
edition = "2021"

[lib]
# ğŸ”¥ [í•µì‹¬] Cë‘ í•©ì²´í•  ë•ŒëŠ” staticlibì´ êµ­ë£°ì…ë‹ˆë‹¤.
crate-type = ["staticlib"]

[dependencies]
cty = "0.2"

[build-dependencies]
bindgen = "0.69"
cc = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true